services:
  - type: web
    name: healthify-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20.x"
      - key: PORT
        value: 5001
      - key: MISTRAL_API_KEY
        generateValue: true # Render will prompt you or use this; it's better to explicitly add it in Render Dashboard
      - key: JWT_SECRET
        generateValue: true # Generates a random secure secret for auth JWT tokens
